### ISSUE TITLE
rlh unit

### ISSUE THREAD

**Issue by michaelcpuckett** [pierreburel/postcss-rem#18]
Could this be tweaked to also include support for the `rlh` unit, which is fairly new and requires a fallback in my case?

**Comment by pierreburel** [comment]
Hello! Unfortunately this would need too much refactoring on both this plugin and [the underlying lib](https://github.com/pierreburel/startijenn-rem) (also the name wouldn't really make sense anymore).

Plus, i'm not sure a pixel fallback makes sense for line height, as it should be unitless for it to scale with font size (when `rlh` is not supported)?

I'm curious what's you use case for `rlh`, as i never used it yet? Would love to have your insight.

**Comment by michaelcpuckett** [comment]
I was using `rlh` for gaps and margins. I ended up switching everything to `rem`s manually. I'm not entirely sure the point of `rlh`, I thought it would help with vertical spacing.

**Comment by pierreburel** [comment]
Oh yeah i think it may help for vertical rhythm, for example to do
```
p { 
  font-size: 1rem; 
  line-height: 1.5; 
  margin-block: 1lh;
}
```
instead of 
```
p { 
  font-size: 1rem; 
  line-height: 1.5; 
  margin-block: 1.5rem; 
}
```

But yeah i don't really see a use case for `rlh` yet, except if you want to make sure this value doesn't change with the current line height. In this case i guess a fallback could be in rem and look like that:
```
:root {
  font-size: 1rem;
  line-height: 1.5;
}

h1,
p {
  margin-block: 3rem; /* 2*1.5 */
  margin-block: 2rlh;
}

h1 {
  font-size: 2rem; 
}
```

But i'm not sure we need a function to convert `px` to `rlh` (since that's what this plugin is for, converting `px` to `rem`), but a plugin that handle the fallback automatically would make sense, but maybe that's more something for a tool like [postcss-preset-env](https://www.npmjs.com/package/postcss-preset-env)? But is it actually needed? [The support looks pretty good](https://caniuse.com/mdn-css_types_length_rlh).
